//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class application
    {
        public int appid { get; set; }
        public int userid { get; set; }
        public int company_id { get; set; }
        public int job_id { get; set; }
        public string resume { get; set; }
        public System.DateTime appdate { get; set; }
        public string appstatus { get; set; }
    }
}
