//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public int compid { get; set; }
        public string compname { get; set; }
        public string compaddress { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    }
}
