//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobpost
    {
        public int jobid { get; set; }
        public int compid { get; set; }
        public string jobtitle { get; set; }
        public string jobdesc { get; set; }
        public string jobtype { get; set; }
        public string jobexperience { get; set; }
        public string jobskills { get; set; }
        public string jobsalary { get; set; }
        public System.DateTime enddate { get; set; }
        public string joblocation { get; set; }
        public string jobstatus { get; set; }
    }
}
