//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class mvcprojectEntities : DbContext
    {
        public mvcprojectEntities()
            : base("name=mvcprojectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<application> applications { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<jobpost> jobposts { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<usertab> usertabs { get; set; }
    
        public virtual int sp_companyreg(Nullable<int> cid, string cname, string caddr, string cphone, string cemail)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var cnameParameter = cname != null ?
                new ObjectParameter("cname", cname) :
                new ObjectParameter("cname", typeof(string));
    
            var caddrParameter = caddr != null ?
                new ObjectParameter("caddr", caddr) :
                new ObjectParameter("caddr", typeof(string));
    
            var cphoneParameter = cphone != null ?
                new ObjectParameter("cphone", cphone) :
                new ObjectParameter("cphone", typeof(string));
    
            var cemailParameter = cemail != null ?
                new ObjectParameter("cemail", cemail) :
                new ObjectParameter("cemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_companyreg", cidParameter, cnameParameter, caddrParameter, cphoneParameter, cemailParameter);
        }
    
        public virtual int sp_userreg(Nullable<int> uid, string uname, string addr, string cemail, string gender, Nullable<System.DateTime> dob, string cphone, string image, string status, string skills, string exp, string edu)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var addrParameter = addr != null ?
                new ObjectParameter("addr", addr) :
                new ObjectParameter("addr", typeof(string));
    
            var cemailParameter = cemail != null ?
                new ObjectParameter("cemail", cemail) :
                new ObjectParameter("cemail", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var cphoneParameter = cphone != null ?
                new ObjectParameter("cphone", cphone) :
                new ObjectParameter("cphone", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("image", image) :
                new ObjectParameter("image", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var skillsParameter = skills != null ?
                new ObjectParameter("skills", skills) :
                new ObjectParameter("skills", typeof(string));
    
            var expParameter = exp != null ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(string));
    
            var eduParameter = edu != null ?
                new ObjectParameter("edu", edu) :
                new ObjectParameter("edu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_userreg", uidParameter, unameParameter, addrParameter, cemailParameter, genderParameter, dobParameter, cphoneParameter, imageParameter, statusParameter, skillsParameter, expParameter, eduParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_logincountid(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_logincountid", unaParameter, pwdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_loginid(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_loginid", unaParameter, pwdParameter);
        }
    
        public virtual int sp_loginsert(Nullable<int> rid, string una, string pw, string utype)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            var utypeParameter = utype != null ?
                new ObjectParameter("utype", utype) :
                new ObjectParameter("utype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_loginsert", ridParameter, unaParameter, pwParameter, utypeParameter);
        }
    
        public virtual ObjectResult<string> sp_logintype(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_logintype", unaParameter, pwdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_maxidlogin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_maxidlogin");
        }
    
        public virtual int sp_jobpost(Nullable<int> compid, string jobtitle, string jobdesc, string jobtype, string jobexp, string jobskills, string jobsal, Nullable<System.DateTime> enddate, string joblocation, string jobstatus)
        {
            var compidParameter = compid.HasValue ?
                new ObjectParameter("compid", compid) :
                new ObjectParameter("compid", typeof(int));
    
            var jobtitleParameter = jobtitle != null ?
                new ObjectParameter("jobtitle", jobtitle) :
                new ObjectParameter("jobtitle", typeof(string));
    
            var jobdescParameter = jobdesc != null ?
                new ObjectParameter("jobdesc", jobdesc) :
                new ObjectParameter("jobdesc", typeof(string));
    
            var jobtypeParameter = jobtype != null ?
                new ObjectParameter("jobtype", jobtype) :
                new ObjectParameter("jobtype", typeof(string));
    
            var jobexpParameter = jobexp != null ?
                new ObjectParameter("jobexp", jobexp) :
                new ObjectParameter("jobexp", typeof(string));
    
            var jobskillsParameter = jobskills != null ?
                new ObjectParameter("jobskills", jobskills) :
                new ObjectParameter("jobskills", typeof(string));
    
            var jobsalParameter = jobsal != null ?
                new ObjectParameter("jobsal", jobsal) :
                new ObjectParameter("jobsal", typeof(string));
    
            var enddateParameter = enddate.HasValue ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(System.DateTime));
    
            var joblocationParameter = joblocation != null ?
                new ObjectParameter("joblocation", joblocation) :
                new ObjectParameter("joblocation", typeof(string));
    
            var jobstatusParameter = jobstatus != null ?
                new ObjectParameter("jobstatus", jobstatus) :
                new ObjectParameter("jobstatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_jobpost", compidParameter, jobtitleParameter, jobdescParameter, jobtypeParameter, jobexpParameter, jobskillsParameter, jobsalParameter, enddateParameter, joblocationParameter, jobstatusParameter);
        }
    
        public virtual ObjectResult<sp_viewjobs_Result> sp_viewjobs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_viewjobs_Result>("sp_viewjobs");
        }
    
        public virtual int sp_jobsearch(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_jobsearch", qryParameter);
        }
    
        public virtual int sp_postapplication(Nullable<int> userid, Nullable<int> company_id, Nullable<int> job_id, string resume, Nullable<System.DateTime> date, string appstatus)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var company_idParameter = company_id.HasValue ?
                new ObjectParameter("company_id", company_id) :
                new ObjectParameter("company_id", typeof(int));
    
            var job_idParameter = job_id.HasValue ?
                new ObjectParameter("job_id", job_id) :
                new ObjectParameter("job_id", typeof(int));
    
            var resumeParameter = resume != null ?
                new ObjectParameter("resume", resume) :
                new ObjectParameter("resume", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var appstatusParameter = appstatus != null ?
                new ObjectParameter("appstatus", appstatus) :
                new ObjectParameter("appstatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_postapplication", useridParameter, company_idParameter, job_idParameter, resumeParameter, dateParameter, appstatusParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_countuserappliedjobwithid(Nullable<int> uid, Nullable<int> jobid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var jobidParameter = jobid.HasValue ?
                new ObjectParameter("jobid", jobid) :
                new ObjectParameter("jobid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_countuserappliedjobwithid", uidParameter, jobidParameter);
        }
    }
}
