//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class usertab
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public System.DateTime dob { get; set; }
        public string phone { get; set; }
        public string image { get; set; }
        public string status { get; set; }
        public string skills { get; set; }
        public string experience { get; set; }
        public string education { get; set; }
    }
}
